seml:
  project_root_dir: /nfs/homedirs/duk/patch_level_dp
  executable: seml/scripts/run_training_classification_experiment.py
  output_dir: seml/output/logs/resnet_mnist
  name: resnet_mnist_experiments

slurm:
  - experiments_per_job: 2
    sbatch_options:
      gres: gpu:1
      cpus-per-task: 5
      time: 00-23:59     # max time, D-HH:MM
      partition: gpu_gtx1080

fixed:
  model_name: "resnet18"
  dataset_name: "mnist"
  dataset_root: "/nfs/shared/data"
  
  max_physical_batch_size: 64
  lr: 0.01
  
  privacy_patch_size: [10, 10]
  padding: 0
  
  check_val_every_n_epoch: 2
  num_sanity_val_steps: 0
  checkpoint_dir: "/nfs/students/duk/checkpoints"

grid:  
  crop_size: 
    type: choice
    options:
      - 13
      - 28

  num_epochs: 
    type: choice
    options:
      - 10
      - 25

  batch_size:
    type: choice
    options:
      - 64
      - 128
      - 256
      - 512
      # - 1024

  clip_norm:
    type: choice
    options:
      - 0.01
      # - 0.02
      # - 0.05
      # - 0.08
      # - 0.1
      # - 1
      # - 10
      # - 100

  epsilon:
    type: choice
    options:
        - 5
        - 10
        - 15
        - 20
        - 30
        - 40
        - 50
        - 60
        - 70
        - 80
        - 90
        - 100

  seed_value:
    type: choice
    options:
      # - 10
      # - 20
      # - 30
      - 516

  baseline_privacy:
    type: choice
    options:
      - False
      - True
