seml:
  project_root_dir: /nfs/homedirs/duk/patch_level_dp
  executable: seml/scripts/run_training_classification_experiment.py
  output_dir: seml/output/logs/simpleconv_dtd
  name: simpleconv_dtd_experiments

slurm:
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:1
      cpus-per-task: 5
      time: 00-23:59     # max time, D-HH:MM
      partition: gpu_gtx1080

fixed:
  model_name: "simpleconv"
  dataset_name: "dtd"
  dataset_root: "/nfs/homedirs/duk/dtd"
  
  max_physical_batch_size: 64
  clip_norm: 1.0
  batch_size: 128
  num_epochs: 100
  lr: 0.01
  
  privacy_patch_size: [10, 10]
  crop_size: 200
  padding: 0
  
  check_val_every_n_epoch: 2
  num_sanity_val_steps: 0
  checkpoint_dir: "/nfs/students/duk/checkpoints"

grid:
  epsilon:
    type: choice
    options:
      - 1
      - 2
      - 4
      - 8
      - 16
      - 32

  seed_value:
    type: choice
    options:
      - 10
      - 20
      - 30
      - 516

  baseline_privacy:
    type: choice
    options:
      - False
      - True
